---
# Source: external-secrets/templates/webhook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-external-secrets-webhook
  namespace: "external-secret"
  labels:
    helm.sh/chart: external-secrets-0.5.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.5.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets-webhook
        app.kubernetes.io/instance: release-name
    spec:
      hostNetwork: false
      serviceAccountName: external-secrets-webhook
      containers:
        - name: webhook
          image: "ghcr.io/external-secrets/external-secrets:v0.5.8"
          imagePullPolicy: IfNotPresent
          args:
          - webhook
          - --port=10250
          - --dns-name=release-name-external-secrets-webhook.external-secret.svc
          - --cert-dir=/tmp/certs
          - --check-interval=5m
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
            - containerPort: 10250
              protocol: TCP
              name: webhook
          readinessProbe:
            httpGet:
              port: 8081
              path: /readyz
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: certs
              mountPath: /tmp/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: release-name-external-secrets-webhook
