---
# Source: external-secrets/templates/webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-external-secrets-webhook
  namespace: "external-secret"
  labels:
    helm.sh/chart: external-secrets-0.5.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.5.8"
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component : webhook
